"""Addressless interaction, addressed access and complete structure."""
from __future__ import annotations
from dataclasses import dataclass
from typing import Callable, Protocol, TypeVar, Generic
from .ontos import Atom, Tuple, Value, atom, tuple_, equals
Path = tuple[Atom, ...]
@dataclass(frozen=True)
class Termination:
    kind: str
    message: str | None = None
class Wire(Protocol):
    async def send(self, message: Value) -> None: ...
class Endpoint(Wire, Protocol):
    def receive(self, handler: Callable[[Value], None]) -> Callable[[], None]: ...
    async def closed(self) -> Termination: ...
    async def close(self) -> None: ...
class AddressedWire(Protocol):
    async def send(self, path: Path, message: Value) -> None: ...
class AddressedEndpoint(AddressedWire, Protocol):
    def receive(self, handler: Callable[[Path, Value], None]) -> Callable[[], None]: ...
    async def closed(self) -> Termination: ...
    async def close(self) -> None: ...
T = TypeVar('T')
@dataclass(frozen=True)
class Parts(Generic[T]):
    own: T
    children: tuple[tuple[Atom, DeixisNode[T]], ...]
class DeixisNode(Protocol[T]):
    def own(self) -> T: ...
    def children(self) -> tuple[tuple[Atom, DeixisNode[T]], ...]: ...
    def at(self, path: Path) -> DeixisNode[T] | None: ...
    def decompose(self) -> Parts[T]: ...
WireTree = DeixisNode[Wire]
__all__ = ['Atom', 'Tuple', 'Value', 'atom', 'tuple_', 'equals', 'Path', 'Termination',
           'Wire', 'Endpoint', 'AddressedWire', 'AddressedEndpoint', 'WireTree', 'Parts', 'DeixisNode']
