import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
const root = fileURLToPath(new URL('../', import.meta.url));
const run = (cmd, args) => execFileSync(cmd, args, { cwd: root, stdio: 'inherit' });
run(process.execPath, ['scripts/links.mjs']);
run(process.execPath, ['scripts/independence.mjs']);
const formatted = execFileSync('gofmt', ['-l', 'wire/go', 'ontos/go'], { cwd: root, encoding: 'utf8' });
if (formatted.trim()) throw new Error('Unformatted Go sources: ' + formatted);
run('go', ['vet', './...']);
run('go', ['test', './...']);
run(process.execPath, ['node_modules/typescript/bin/tsc', '-p', 'wire/ts/tsconfig.check.json']);
run(process.execPath, ['node_modules/typescript/bin/tsc', '-p', 'wire/ts/tsconfig.build.json']);
run(process.execPath, ['scripts/conformance.mjs']);
